config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    get '/rainbow' => 'unicorns#rainbow', status: 'rainbow', as: :rainbow 
  end

  resources :unicorns do
    resources :superpowers do
      resources :reviews
    end
  end
  root to: 'static#home'  
  get '/auth/:provider/callback', to: 'sessions#omniauth'


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_account.rb
class GoogleAccount < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :superpower
end

app/models/superpower.rb
class Superpower < ApplicationRecord
    validates :type, :description, presence: true
    belongs_to :unicorn
    has_many :reviews
    self.inheritance_column = :_type_disabled
end

app/models/unicorn.rb
class Unicorn < ApplicationRecord
    validates :name, :age, :color, :personality, :quirks, presence: true
    has_many :superpowers
    has_many :reviews, through: :superpowers
    belongs_to :user
    scope :rainbow, -> { where(color: 'rainbow') }
end

app/models/user.rb
class User < ApplicationRecord
  
  # has_secure_password # validation presence of password
  has_many :unicorns
  has_many :google_accounts
  has_many :superpowers, through: :unicorns
  has_many :reviews, through: :superpowers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!, except: [:omniauth]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :find_superpower
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :find_unicorn
    
    def index
    end

    def new 
        @review = Review.new
    end

    def create 
        @review = Review.new(review_params)
        @review.superpower_id = @superpower.id
        @review.unicorn_id = current_user.id
        if @review.save
            redirect_to user_unicorn_path(current_user.id, @unicorn.id)
        else
            render 'new'
        end
    end

    def edit
    end

    def update 

        if @review.update(review_params)
            redirect_to user_unicorn_path(current_user.id, @unicorn.id)
        else
            render 'edit'
        end
    end

    def destroy
        @review.destroy
        redirect_to user_unicorn_path(current_user, @unicorn.id)	
    end

    private

    def find_unicorn
        @unicorn = Unicorn.find(params[:unicorn_id])
    end

    def find_review
        @review = Review.find(params[:id])
    end

    def find_superpower
        @superpower = Superpower.find(params[:superpower_id])
    end

    def review_params 
        params.require(:review).permit(:rating, :comment)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # in charge of loggin user in/out & oumniauth
    # creating or destroying a sesssion

    # skip_before_action :verified_user, only: [:new, :create]

    def omniauth
        
        user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do  |u|
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(16)
        end
        
        if user.valid?
            sign_in_and_redirect user
        else
            flash[:message] = user.errors.full_messages.join(" ,")
            redirect_to root_path
        end      
    end

    def signup
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to movies_path
        else 
            @error = @user.errors.full_messages
            render :signup
        end 
    end

    def logout 
        session.clear
        redirect_to root_path
    end 
 
    def auth
        request.env['omniauth.auth']
    end 
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    skip_before_action :authenticate_user!, only: %i[home]
    
    def home 
    end
end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController

    def create
		@unicorn = Unicorn.find(params[:unicorn_id])
	 	@superpower = @unicorn.superpowers.create(params[:superpower].permit(:type, :description))
		redirect_to user_unicorn_path(current_user.id, @unicorn)	
	end

	def new
		@unicorn = Unicorn.find(params[:unicorn_id])
	end

    def destroy
		@unicorn = Unicorn.find(params[:unicorn_id])
		@superpower = @unicorn.superpowers.find(params[:id])
		@superpower.destroy
		redirect_to user_unicorn_path(current_user.id, @unicorn)
	end
end

app/controllers/unicorns_controller.rb
class UnicornsController < ApplicationController

    before_action :find_unicorn, only: [:show, :update, :edit, :destroy]


    def index
        @unicorns = current_user.unicorns.order("created_at DESC")
    end

    def rainbow
        @rainbow_unicorns = current_user.unicorns.rainbow
    end

    def new 
        @unicorn = Unicorn.new
    end

    def create
        @user = User.find(current_user.id)
        @unicorn = @user.unicorns.create(unicorn_params)

        if @unicorn.save
            redirect_to user_unicorns_path(current_user.id)
        else
            render 'new'
        end
        
    end

    def show
        unless current_user.id == @unicorn.user_id
            flash[:notice] = "You don't have access to that unicorn!"
            redirect_to user_unicorns_path(current_user.id)
            return
        end
    end

    def update

        if @unicorn.update(unicorn_params)
            redirect_to @unicorn
        else
            render 'edit'
        end
    end

    def edit 
    end

    def destroy
        @unicorn.destroy
        redirect_to user_unicorns_path(current_user.id)
    end

    private 


    def unicorn_params
        params.require(:unicorn).permit(:name, :age, :color, :personality, :quirks)
    end

    def find_unicorn
        @unicorn = Unicorn.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    skip_before_action :verified_user, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(username:params[:username])
        if !@user
            @error = "I'm sorry, that username is incorrect"
            render :new
        elsif !user.authenticate(params[:password])
            @error =  "Password was Incorrect"
            render :new  
        else 
            session[:user_id] = @user.id
            redirect_to unicorns_path 
        end 
    end
  end 


  private 
  def user_params
    params.require(:user).permit(:username,:password)
  end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/superpowers_helper.rb
module SuperpowersHelper
end

app/helpers/unicorns_helper.rb
module UnicornsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_form.html.erb
<h1> Here's Your Review </h1>
<%= simple_form_for ([@unicorn , @superpower, @review]) do |f| %>

<%= f.input :rating %>
<%= f.input :comment %>
<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

<script>
$(‘#rating-form’).raty({
path: ‘/assets/’,
scoreName: ‘review[rating]’
});
</script>

app/views/reviews/_review.html.erb
<div class="review">
    <p><div id = “rating-form”> <label> Rating</label> </div></p>
	<p class="review-comment"><%= review.comment %></p>
    <% if user_signed_in? %>


			<div class="links btn-group">
            <%= link_to "Edit", edit_unicorn_superpower_review_path(@unicorn, review.superpower, review) %>
            <%= link_to "Delete", unicorn_superpower_review_path(@unicorn, review.superpower, review), method: :delete, data: {confirm: "Are you sure?"} %>	

	<% end %>

    <script>
$(‘#rating-form’).raty({
path: ‘/assets/’,
scoreName: ‘review[rating]’
});
</script>
</div>	

app/views/reviews/edit.html.erb
<h1> Edit Review </h1>

<%= simple_form_for([@unicorn, @superpower, @review]) do |f|%>
<%= f.input :rating %>
<%= f.input :comment %>
<%= f.button :submit %>

<% end %>

app/views/reviews/index.html.erb
<%= render 'form' %>

app/views/reviews/new.html.erb
<h1> New Review </h1>

<%= render 'form' %>

app/views/superpowers/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= superpower.type %>:</strong>
          <%= superpower.description %>
        </p>
      </div>
    </div>
     <%= link_to 'Delete', [superpower.unicorn, superpower],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>

</div>

app/views/superpowers/_form.html.erb
<%= simple_form_for([@unicorn, @unicorn.superpowers.build]) do |f| %>
    <!--
    collection.build(attributes = {}, …) Returns one or more new objects of the collection type that have been instantiated with attributes and linked to this object through a foreign key, but have not yet been saved. Note: This only works if an associated object already exists, not if it‘s nil!
    -->
    <div class="field">
      <div class="control">
        <%= f.input :type, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
      </div>
    </div>
    
    <div class="field">
      <div class="control">
        <%= f.input :description, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }  %>
      </div>
    </div>

 
    <%= f.button :submit, 'Create a Superpower', class: "button is-primary" %>
    <% end %>

app/views/superpowers/_superpower.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= superpower.type %>:</strong>
          <%= superpower.description %>
        </p>
      </div>
    </div>
    <%= render superpower.reviews %>
    <div>
    <%= link_to "Add Review", new_unicorn_superpower_review_path(@unicorn, superpower) %>
    </div>
     <%= link_to 'Delete', [superpower.unicorn, superpower],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>

</div>

app/views/superpowers/new.html.erb
<% content_for :page_title, "‧༓☾Create A New Superpower ☽༓" %>

<%= render 'form' %>

app/views/unicorns/_form.html.erb
<div class="section">
  <%= simple_form_for [@unicorn] do |f| %>
  <div class="field">
     <div class="control">
     <%= f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
     </div>
  </div>
  <div class="field">
     <div class="control">
     <%= f.input :age, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
     </div>
  </div>
  <div class="field">
  <div class="control">
  <%= f.input :color, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
  </div>
</div>
<div class="field">
<div class="control">
<%= f.input :personality, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
</div>
</div>
<div class="field">
<div class="control">
<%= f.input :quirks, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
</div>
</div>
  <%= f.button :submit, 'Create Unicorn', class: "button is-primary" %>
  <% end %>
</div>

app/views/unicorns/edit.html.erb
<% content_for :page_title, "Edit Unicorn" %>

<div class="section">
  <%= simple_form_for @unicorn do |f| %>
  <div class="field">
     <div class="control">
     <%= f.input :name, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
     </div>
  </div>
  <div class="field">
     <div class="control">
     <%= f.input :age, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
     </div>
  </div>
  <div class="field">
  <div class="control">
  <%= f.input :color, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
  </div>
</div>
<div class="field">
<div class="control">
<%= f.input :personality, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
</div>
</div>
<div class="field">
<div class="control">
<%= f.input :quirks, input_html: {class: 'input'}, wrapper: false, label_html: {class: 'label'} %>
</div>
</div>
  <%= f.button :submit, 'Edit Unicorn', class: "button is-primary" %>
  <% end %>
</div>

app/views/unicorns/index.html.erb
<%= flash[:message]%>

<% content_for :page_title, "Unicorns" %>

<div class="section">
	<div class="container">
		<% @unicorns.each do |unicorn| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to unicorn.name, unicorn_path(unicorn)  %></p>
		      </div>
		    </div>
		  </div>
		</div>
		<% end %>
	</div>
</div>

app/views/unicorns/new.html.erb
<% content_for :page_title, "‧༓☾Create A New Unicorn ☽༓" %>

<%= render 'form' %>

app/views/unicorns/rainbow.html.erb
<%= flash[:message]%>

<% content_for :page_title, "Unicorns" %>

<div class="section">
	<div class="container">
		<% @rainbow_unicorns.each do |unicorn| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to unicorn.name, unicorn_path(unicorn)  %></p>
		      </div>
		    </div>
		  </div>
		</div>
		<% end %>
	</div>
</div>

app/views/unicorns/show.html.erb
<% content_for :page_title, "ﾟ･✧*"+@unicorn.name + "*✧･ﾟ" %>


<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong>Actions</strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_unicorn_path(@unicorn), class:"button" %>
		  	</p>
		  	<p class="level-item">
				<%= link_to "Delete", unicorn_path(@unicorn), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>

		<div class="name">
        <b>Name:</b> <%= @unicorn.name %>
		</div>
        <div class="age">
        <b>Age:</b> <%= @unicorn.age %>
		</div>
        <div class="color">
		<b>Color:</b> <%= @unicorn.color %>
		</div>
        <div class="personality">
		<b>Personality:</b> <%= @unicorn.personality %>
		</div>
        <div class="quirks">
		<b>Quirks:</b> <%= @unicorn.quirks %>
		</div>
	</div>

	<section class="section superpowers">
	<div class="container">
		<h2 class="subtitle is-5"><strong><%= @unicorn.superpowers.count %></strong> Superpowers</h2>
		<%= render @unicorn.superpowers %>
		<div class="comment-form">
			<hr />
			<%= link_to "Create a Superpower", new_unicorn_superpower_path(@unicorn)%>
	</div>

</section>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_with(model: @user, local: true) do |f| %>
 
    <div class="form-group">
      <%= f.label :username %><br/>
      <%= f.text_field :username, class: "form-control" %>
    </div>
     
    <div class="form-group">
      <%= f.label :password %><br/>
      <%= f.password_field :password, class: "form-control" %>
    </div>
     
    <div class="form-group">
      <%= f.submit %>
    </div>
     
    <% end %>