config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    get '/rainbow' => 'unicorns#rainbow', status: 'rainbow', as: :rainbow 
  end

  resources :unicorns do
    resources :superpowers do
      resources :reviews
    end
  end
  root to: 'static#home'  
  get '/auth/:provider/callback', to: 'sessions#omniauth'


end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_account.rb
class GoogleAccount < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :superpower
end

app/models/superpower.rb
class Superpower < ApplicationRecord
    validates :type, :description, presence: true
    belongs_to :unicorn
    has_many :reviews
    self.inheritance_column = :_type_disabled
end

app/models/unicorn.rb
class Unicorn < ApplicationRecord
    validates :name, :age, :color, :personality, :quirks, presence: true
    has_many :superpowers
    has_many :reviews, through: :superpowers
    belongs_to :user
    scope :rainbow, -> { where(color: 'rainbow') }
end

app/models/user.rb
class User < ApplicationRecord
  
  # has_secure_password # validation presence of password
  has_many :unicorns
  has_many :google_accounts
  has_many :superpowers, through: :unicorns
  has_many :reviews, through: :superpowers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authenticate_user!, except: [:omniauth]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :find_superpower
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :find_unicorn
    
    def index
    end

    def new 
        @review = Review.new
    end

    def create 
        @review = Review.new(review_params)
        @review.superpower_id = @superpower.id
        @review.unicorn_id = current_user.id
        if @review.save
            redirect_to user_unicorn_path(current_user.id, @unicorn.id)
        else
            render 'new'
        end
    end

    def edit
    end

    def update 

        if @review.update(review_params)
            redirect_to user_unicorn_path(current_user.id, @unicorn.id)
        else
            render 'edit'
        end
    end

    def destroy
        @review.destroy
        redirect_to user_unicorn_path(current_user, @unicorn.id)	
    end

    private

    def find_unicorn
        @unicorn = Unicorn.find(params[:unicorn_id])
    end

    def find_review
        @review = Review.find(params[:id])
    end

    def find_superpower
        @superpower = Superpower.find(params[:superpower_id])
    end

    def review_params 
        params.require(:review).permit(:rating, :comment)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # in charge of loggin user in/out & oumniauth
    # creating or destroying a sesssion

    # skip_before_action :verified_user, only: [:new, :create]

    def omniauth
        
        user = User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do  |u|
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(16)
        end
        
        if user.valid?
            sign_in_and_redirect user
        else
            flash[:message] = user.errors.full_messages.join(" ,")
            redirect_to root_path
        end      
    end

    def signup
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            redirect_to movies_path
        else 
            @error = @user.errors.full_messages
            render :signup
        end 
    end

    def logout 
        session.clear
        redirect_to root_path
    end 
 
    def auth
        request.env['omniauth.auth']
    end 
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    skip_before_action :authenticate_user!, only: %i[home]
    
    def home 
    end
end

app/controllers/unicorns_controller.rb
class UnicornsController < ApplicationController

    before_action :find_unicorn, only: [:show, :update, :edit, :destroy]


    def index
        @unicorns = current_user.unicorns.order("created_at DESC")
    end

    def rainbow
        @rainbow_unicorns = current_user.unicorns.rainbow
    end

    def new 
        @unicorn = Unicorn.new
    end

    def create
        @user = User.find(current_user.id)
        @unicorn = @user.unicorns.create(unicorn_params)

        if @unicorn.save
            redirect_to user_unicorns_path(current_user.id)
        else
            render 'new'
        end
        
    end

    def show
        unless current_user.id == @unicorn.user_id
            flash[:notice] = "You don't have access to that unicorn!"
            redirect_to user_unicorns_path(current_user.id)
            return
        end
    end

    def update

        if @unicorn.update(unicorn_params)
            redirect_to @unicorn
        else
            render 'edit'
        end
    end

    def edit 
    end

    def destroy
        @unicorn.destroy
        redirect_to user_unicorns_path(current_user.id)
    end

    private 


    def unicorn_params
        params.require(:unicorn).permit(:name, :age, :color, :personality, :quirks)
    end

    def find_unicorn
        @unicorn = Unicorn.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    skip_before_action :verified_user, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(username:params[:username])
        if !@user
            @error = "I'm sorry, that username is incorrect"
            render :new
        elsif !user.authenticate(params[:password])
            @error =  "Password was Incorrect"
            render :new  
        else 
            session[:user_id] = @user.id
            redirect_to unicorns_path 
        end 
    end
  end 


  private 
  def user_params
    params.require(:user).permit(:username,:password)
  end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/superpowers_helper.rb
module SuperpowersHelper
end

app/helpers/unicorns_helper.rb
module UnicornsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>UnicornApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <section class="hero is-primary is-medium">
	  <!-- Hero head: will stick at the top -->
	  <div class="hero-head">
	    <nav class="navbar">
	      <div class="container">
	        <div class="navbar-brand">
			<% if  current_user %>
	          <%= link_to 'Unicorns', unicorns_path, class: "navbar-item" %>
	          <span class="navbar-burger burger" data-target="navbarMenuHeroA">
	            <span></span>
	            <span></span>
	            <span></span>
	          </span>
	        </div>
	        <div id="navbarMenuHeroA" class="navbar-menu">
	          <div class="navbar-end">
			  
	            <%= link_to "Create New Unicorn", new_unicorn_path, class:"navbar-item" %>
	          </div>
			<% end %>
	        </div>
	      </div>
	    </nav>
	  </div>

	  <!-- Hero content: will be in the middle -->
	  <div class="hero-body">
	    <div class="container has-text-centered">
	      <h1 class="title">
	        <%= yield :page_title %>
	      </h1>
	    </div>
	  </div>
	</section>
    <%= yield %>
  </body>
  <body> 
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if  user_signed_in? %>
	<%= current_user.email %>
	<%= link_to 'Rainbow Unicorns', user_rainbow_path(current_user.id)%>
	<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
	<%= link_to 'Account Settings', edit_user_registration_path%>
  <% else %>
    <%= link_to 'Log in', new_user_session_path %>
	<%= button_to "Google Log in", "/auth/google_oauth2", method: :post, class: "btn btn-primary" %>
	<%= link_to 'Sign up', new_user_registration_path %>
  <% end %>


  </body>
</html>